#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] if "tools" in str(Path(__file__).resolve()) else Path.cwd()

files = {
    "app/src/main/java/com/example/vibrationmonitor/MainActivity.java": {
        "가속도 센서 준비 완료": "Czujnik przyspieszenia gotowy",
        "가속도 센서를 찾을 수 없습니다.": "Nie znaleziono czujnika przyspieszenia.",
        "GPS : 위치 확인 대기 중": "GPS : oczekiwanie na lokalizację",
        "카메라 : 준비 중...": "Kamera : przygotowanie...",
        "사용 건물": "Budynek / obszar",
        "현재값 : 0.000 m/s²": "Aktualna : 0.000 m/s²",
        "평균값 : 0.000 m/s²": "Średnia : 0.000 m/s²",
        "최대값 : 0.000 m/s²": "Maks. : 0.000 m/s²",
        "최소값 : 0.000 m/s²": "Min. : 0.000 m/s²",
        "주 진동 방향 : -": "Główny kierunek drgań : -",
        "상태 : 정상": "Stan : normalny",
        "이벤트 : 0회\\n최근 3초 데이터 대기 중": "Zdarzenia : 0\\nOczekiwanie na ostatnie 3 s danych",
        "SPEC 저장 / 적용": "ZAPISZ / ZASTOSUJ SPEC",
        "SPEC %.2f m/s² 저장 완료": "SPEC %.2f m/s² zapisano",
        "0보다 큰 숫자를 입력하세요.": "Wprowadź liczbę większą od 0.",
        "알람 수신 이메일": "E-mail do alarmów",
        "이메일 저장": "Zapisz e-mail",
        "이메일 주소가 비어 있습니다.": "Adres e-mail jest pusty.",
        "알람 이메일 저장 완료": "Adres alarmowy zapisano",
        "측정 시작": "START POMIARU",
        "측정 중지": "STOP POMIARU",
        "값 초기화": "RESET WARTOŚCI",
        "저장된 CSV 파일": "Zapisane pliki CSV",
        "공정 충격 분석 / PROCESS SHOCK": "Analiza uderzeń procesu / PROCESS SHOCK",
        "진동 이력 관리": "Historia drgań",
        "저장된 CSV 파일이 없습니다.": "Brak zapisanych plików CSV.",
        "확인": "OK",
        "닫기": "Zamknij",
        "Telegram 자동 알림": "Automatyczne alarmy Telegram",
        "Telegram Bot Token": "Token bota Telegram",
        "Telegram Chat ID 여러 개 입력 (쉼표 또는 줄바꿈 구분)": "Wprowadź kilka Chat ID (oddziel przecinkiem lub nową linią)",
        "Telegram 저장": "Zapisz Telegram",
        "Telegram 테스트 전송": "Wyślij test Telegram",
        "Telegram : 설정 필요": "Telegram : wymagana konfiguracja",
        "Telegram : 설정 저장됨": "Telegram : konfiguracja zapisana",
        "Bot Token과 Chat ID를 입력해주세요.": "Wprowadź Bot Token i Chat ID.",
        "Telegram 설정을 저장했습니다.": "Konfiguracja Telegram została zapisana.",
        "먼저 Bot Token과 Chat ID를 입력해주세요.": "Najpierw wprowadź Bot Token i Chat ID.",
        "Telegram : 테스트 전송 중...": "Telegram : wysyłanie testu...",
        "Telegram : 테스트 전송 성공": "Telegram : test wysłany pomyślnie",
        "Telegram 테스트 메시지 전송 성공": "Wiadomość testowa Telegram wysłana",
        "Telegram : 전송 실패 (": "Telegram : błąd wysyłania (",
        "Telegram 전송 실패: ": "Błąd wysyłania Telegram: ",
        "REAL-TIME 3-AXIS CONDITION MONITORING": "MONITOROWANIE DRGAŃ 3-OSIOWE W CZASIE RZECZYWISTYM",
        "AREA": "OBSZAR",
        "LIVE VIBRATION": "DRGANIA NA ŻYWO",
        "TOTAL VIBRATION": "DRGANIA CAŁKOWITE",
        "SPEC APPLY": "ZASTOSUJ SPEC",
        "▶  측정 시작": "▶  START POMIARU",
        "■  측정 중지": "■  STOP POMIARU",
        "↻  값 초기화": "↻  RESET WARTOŚCI",
        "CSV 데이터": "DANE CSV",
        "⚡  공정 충격 분석 / PROCESS SHOCK": "⚡  ANALIZA UDERZEŃ / PROCESS SHOCK",
        "⚙  알림 / Telegram 설정": "⚙  USTAWIENIA ALARMÓW / TELEGRAM",
        "▲  알림 / Telegram 설정 닫기": "▲  ZAMKNIJ USTAWIENIA TELEGRAM",
        "카메라 : 권한 필요": "Kamera : wymagane uprawnienie",
        "카메라 : 촬영 완료": "Kamera : zdjęcie zapisane",
        "카메라 : 파일 저장 실패": "Kamera : błąd zapisu pliku",
        "카메라 : 파일 저장 오류": "Kamera : błąd zapisu",
        "카메라 : 준비 완료": "Kamera : gotowa",
        "카메라 : 준비 실패": "Kamera : błąd inicjalizacji",
        "카메라 : 촬영 준비 대기...": "Kamera : oczekiwanie na gotowość...",
        "카메라 : 촬영 실패(준비 안됨)": "Kamera : zdjęcie nieudane (brak gotowości)",
        "카메라 : 촬영 중...": "Kamera : wykonywanie zdjęcia...",
        "카메라 : 사진 처리 중...": "Kamera : przetwarzanie zdjęcia...",
        "카메라 : 촬영 실패": "Kamera : zdjęcie nieudane",
        "카메라 : 촬영 오류": "Kamera : błąd zdjęcia",
        "GPS : 위치 권한 허용 필요": "GPS : wymagane uprawnienie lokalizacji",
        "GPS : 위치 신호 검색 중...": "GPS : wyszukiwanie sygnału...",
        "GPS : 위치 확인 오류": "GPS : błąd lokalizacji",
        "GPS : 위치 권한 거부됨": "GPS : odmowa uprawnienia lokalizacji",
        "카메라 : 권한 허용됨": "Kamera : uprawnienie przyznane",
        "카메라 : 권한 거부됨": "Kamera : odmowa uprawnienia",
        "사진 자동 촬영을 사용하려면 카메라 권한이 필요합니다.": "Automatyczne zdjęcia wymagają uprawnienia do kamery.",
        "미지정": "Nieokreślone",
        "센서 없음": "Brak czujnika",
        "상태 : 측정 중": "Stan : pomiar",
        "상태 : 정지": "Stan : zatrzymany",
        "주 진동 방향 : ": "Główny kierunek drgań : ",
        "축": "oś",
        "현재값 : %.3f m/s²": "Aktualna : %.3f m/s²",
        "평균값 : %.3f m/s²": "Średnia : %.3f m/s²",
        "최대값 : %.3f m/s²": "Maks. : %.3f m/s²",
        "최소값 : %.3f m/s²": "Min. : %.3f m/s²",
        "⚠ SPEC 초과 : %.3f": "⚠ Przekroczenie SPEC : %.3f",
        "회\\n초과 후 3초 데이터 기록 중...": " razy\\nZapisywanie 3 s danych po przekroczeniu...",
        "회\\n최근 이벤트 데이터 : ": " razy\\nDane ostatniego zdarzenia : ",
        "개 확보 완료": " próbek zapisano",
        "기록 없음": "Brak zapisu",
        "🚨 Vibration SPEC 초과 알람\\n\\n": "🚨 Alarm przekroczenia SPEC drgań\\n\\n",
        "건물 : ": "Budynek : ",
        "발생시간 : ": "Czas zdarzenia : ",
        "SPEC 초과량 : %.3f m/s²\\n": "Przekroczenie SPEC : %.3f m/s²\\n",
        "데이터 수 : ": "Liczba danych : ",
        "개": " szt.",
        "📍 같은 이벤트의 LGES ": "📍 Lokalizacja GPS LGES tego samego zdarzenia ",
        " GPS 위치": " GPS",
        "Telegram 위치 맵 전송 성공": "Mapa lokalizacji wysłana przez Telegram",
        "Telegram 위치 맵 전송 실패 : ": "Błąd wysyłania mapy Telegram : ",
        "Telegram 이벤트 묶음 전송 성공": "Pakiet zdarzenia wysłany przez Telegram",
        "Telegram 이벤트 묶음 전송 실패: ": "Błąd wysyłania pakietu Telegram: ",
        "상태 : 이벤트 기록 완료": "Stan : zapis zdarzenia zakończony",
        "없음": "Brak",
        "사진 : ": "Zdjęcie : ",
        "사용 가능한 이메일 앱을 찾지 못했습니다.": "Nie znaleziono aplikacji e-mail.",
        "CSV 읽기 오류": "Błąd odczytu CSV",
        "표시할 데이터가 없습니다.": "Brak danych do wyświetlenia.",
        "파일 : ": "Plik : ",
        "\\n데이터 수 : ": "\\nLiczba danych : ",
        "\\n평균값 : %.3f m/s²": "\\nŚrednia : %.3f m/s²",
        "\\n최대값 : %.3f m/s²": "\\nMaks. : %.3f m/s²",
        "\\n최소값 : %.3f m/s²": "\\nMin. : %.3f m/s²",
        "\\nSPEC : %.2f m/s²": "\\nSPEC : %.2f m/s²",
        "저장 진동 데이터": "Zapisane dane drgań",
    },
    "app/src/main/java/com/example/vibrationmonitor/HistoryActivity.java": {
        "미지정": "Nieokreślone",
        "진동 이력 관리": "Historia drgań",
        "현재 SPEC : %.2f m/s²": "Aktualny SPEC : %.2f m/s²",
        "저장 이벤트 : ": "Zapisane zdarzenia : ",
        "건": "",
        "\\n저장된 CSV 이벤트가 없습니다.": "\\nBrak zapisanych zdarzeń CSV.",
        "이벤트 최대 진동 Trend": "Trend maksymalnych drgań zdarzeń",
        "\\n최근 이벤트": "\\nOstatnie zdarzenia",
        "이벤트 #": "Zdarzenie #",
        "\\nSPEC %.2f   초과 +%.3f m/s²": "\\nSPEC %.2f   przekroczenie +%.3f m/s²",
        "\\n데이터 %,d개": "\\nDane: %,d",
        "통계 대시보드": "Panel statystyk",
        "돌아가기": "Wstecz",
        "\\n파일 : ": "\\nPlik : ",
        "\\n건물 : ": "\\nBudynek : ",
        "\\n데이터 수 : ": "\\nLiczba danych : ",
        "개": " szt.",
        "\\n평균값 : %.3f m/s²": "\\nŚrednia : %.3f m/s²",
        "\\n최대값 : %.3f m/s²": "\\nMaks. : %.3f m/s²",
        "\\n최소값 : %.3f m/s²": "\\nMin. : %.3f m/s²",
        "\\n현재 SPEC : %.2f m/s²": "\\nAktualny SPEC : %.2f m/s²",
        "\\nSPEC 초과량 : %.3f m/s²": "\\nPrzekroczenie SPEC : %.3f m/s²",
        "\\nGPS 위치 : %.6f, %.6f": "\\nPozycja GPS : %.6f, %.6f",
        "\\nGPS 위치 : 기록 없음": "\\nPozycja GPS : brak zapisu",
        "\\nLGES WA5 이벤트 위치": "\\nLokalizacja zdarzenia LGES WA5",
        "\\n이벤트 자동 촬영 사진": "\\nAutomatyczne zdjęcie zdarzenia",
        "이벤트 상세 그래프": "Szczegółowy wykres zdarzenia",
        "닫기": "Zamknij",
        "이벤트 위치": "Lokalizacja zdarzenia",
        "GPS 오차 또는 건물 범위 밖": "Błąd GPS lub poza obszarem budynku",
    },
    "app/src/main/java/com/example/vibrationmonitor/StatisticsActivity.java": {
        "진동 통계 대시보드": "Panel statystyk drgań",
        "현재 SPEC : %.2f m/s²": "Aktualny SPEC : %.2f m/s²",
        "오늘": "Dzisiaj",
        "7일": "7 dni",
        "30일": "30 dni",
        "돌아가기": "Wstecz",
        "최근 7일": "Ostatnie 7 dni",
        "최근 30일": "Ostatnie 30 dni",
        "\\n조회 기간 : ": "\\nOkres : ",
        "\\n해당 기간에 저장된 이벤트가 없습니다.": "\\nBrak zapisanych zdarzeń w tym okresie.",
        "판정 : ": "Ocena : ",
        "이벤트 수": "Liczba zdarzeń",
        "건": "",
        "기간 최대값": "Maksimum okresu",
        "이벤트 평균값": "Średnia zdarzeń",
        "SPEC 초과 이벤트": "Zdarzenia > SPEC",
        "SPEC 초과율": "Wskaźnik przekroczeń SPEC",
        "\\n날짜별 MAX / AVG Trend": "\\nTrend MAX / AVG wg daty",
        "\\n날짜별 요약": "\\nPodsumowanie wg daty",
        "\\nMAX %.3f   AVG %.3f   초과 %d/%d건": "\\nMAX %.3f   AVG %.3f   ponad SPEC %d/%d",
    },
    "app/src/main/java/com/example/vibrationmonitor/ProcessShockActivity.java": {
        "PROCESS SHOCK\\nPROFILER": "PROFIL UDERZEŃ\\nPROCESU",
        "FIELD ANALYZER · CONTINUOUS IMPACT BLACKBOX": "ANALIZATOR TERENOWY · CIĄGŁY REJESTRATOR UDERZEŃ",
        "● READY": "● GOTOWY",
        "CAMERA : CHECKING...": "KAMERA : SPRAWDZANIE...",
        "LINE": "LINIA",
        "EQUIPMENT": "URZĄDZENIE",
        "PROCESS": "PROCES",
        "AUTO TIMELINE": "AUTOMATYCZNA OŚ CZASU",
        "MANUAL UNIT": "RĘCZNY MODUŁ",
        "UNIT": "MODUŁ",
        "UNIT SEGMENT : READY": "SEGMENT MODUŁU : GOTOWY",
        "REAL 00:00 · PROCESS 00:00 · READY": "RZECZ. 00:00 · PROCES 00:00 · GOTOWY",
        "PAUSE": "PAUZA",
        "TOTAL IMPACT": "UDERZENIE CAŁKOWITE",
        "PROCESS / IMPACT TIMELINE": "OŚ CZASU PROCESU / UDERZEŃ",
        "LAST IMPACT : -\\n이벤트 발생 시 사진 · 전후 트렌드 · CSV · 요약을 자동 저장합니다.": "OSTATNIE UDERZENIE : -\\nPo zdarzeniu automatycznie zapisywane są zdjęcie, trend, CSV i podsumowanie.",
        "EVENT HISTORY": "HISTORIA ZDARZEŃ",
        "DATA DOWNLOAD": "POBIERZ DANE",
        "REMOTE VIEW": "PODGLĄD ZDALNY",
        "START MONITORING": "START MONITOROWANIA",
        "STOP & ANALYZE": "STOP I ANALIZA",
        "측정 중에는 MCSC를 변경할 수 없습니다.": "Nie można zmieniać MCSC podczas pomiaru.",
        "AUTO STOP CORRECTION": "AUTOMATYCZNA KOREKCJA STOP",
        "저진동 상태가 3초 이상 지속되면 설비 정지 후보로 보고 PROCESS 시간만 자동 보정합니다. ": "Jeśli niski poziom drgań trwa ponad 3 s, system traktuje to jako możliwy postój i koryguje tylko czas procesu. ",
        "공정 자체에 3초 이상의 정숙 구간이 많으면 OFF로 사용하세요.": "Jeśli proces ma wiele naturalnych cichych odcinków >3 s, użyj trybu OFF.",
        "MCSC · UNIT TIME MAP": "MCSC · MAPA CZASÓW MODUŁÓW",
        "ENGINEER MCSC · 0.1초 단위 설정\\n": "MCSC DLA INŻYNIERA · krok 0,1 s\\n",
        "한 줄에 Unit 이름, 기준시간(초)\\n": "W każdym wierszu: nazwa modułu, czas bazowy (s)\\n",
        "설비가 멈추면 PROCESS PAUSE를 누르면\\n": "Gdy urządzenie się zatrzyma, naciśnij PROCESS PAUSE\\n",
        "진동 측정은 계속하고 공정시간만 멈춥니다.": "Pomiar drgań trwa dalej, zatrzymuje się tylko czas procesu.",
        "저장": "Zapisz",
        "MCSC 형식을 확인해주세요.": "Sprawdź format MCSC.",
        "개 Unit 저장 완료": " modułów zapisano",
        "취소": "Anuluj",
        "AUTO TIMELINE · ": "AUTO OŚ CZASU · ",
        " Units · ": " modułów · ",
        "MANUAL UNIT · READY": "RĘCZNY MODUŁ · GOTOWY",
        "RESUME": "WZNÓW",
        "● MANUAL LINE STOP · PROCESS TIME PAUSED": "● RĘCZNY STOP LINII · CZAS PROCESU WSTRZYMANY",
        "● MONITORING · AUTO TIMELINE · MANUAL OVERRIDE": "● MONITORING · AUTO OŚ CZASU · RĘCZNE NADPISANIE",
        "● AUTO LINE STOP #": "● AUTO STOP LINII #",
        " · TIMELINE HOLD": " · OŚ CZASU WSTRZYMANA",
        "● AUTO RESUME · CORRECTED %.1fs": "● AUTO WZNOWIENIE · KOREKTA %.1fs",
        "● STOP CANDIDATE %.1fs · AUTO CORR ARMED": "● MOŻLIWY STOP %.1fs · AUTO KOREKTA AKTYWNA",
        "● MONITORING · AUTO TIMELINE": "● MONITORING · AUTO OŚ CZASU",
        "가속도 센서가 없습니다.": "Brak czujnika przyspieszenia.",
        "AUTO TIMELINE MCSC가 없습니다.": "Brak mapy MCSC dla automatycznej osi czasu.",
        "UNIT SEGMENT : CALIBRATING": "SEGMENT MODUŁU : KALIBRACJA",
        "LAST IMPACT : -\\n측정 중 공정/UNIT을 변경하면 구간별 Peak/RMS/Impact를 자동 비교합니다.": "OSTATNIE UDERZENIE : -\\nZmiana procesu/modułu podczas pomiaru automatycznie porównuje Peak/RMS/Impact.",
        "REAL 00:00 · PROCESS 00:00 · CALIBRATING": "RZECZ. 00:00 · PROCES 00:00 · KALIBRACJA",
        "● STOPPED / ANALYSIS READY": "● ZATRZYMANO / GOTOWY DO ANALIZY",
        "Background monitor 시작 실패: ": "Błąd uruchomienia monitoringu w tle: ",
        "● MONITORING · MANUAL UNIT": "● MONITORING · MODUŁ RĘCZNY",
        "센서 안정화 완료 · 연속 공정 감시 시작": "Stabilizacja czujnika zakończona · start ciągłego monitoringu procesu",
        "· PAUSED": "· PAUZA",
        "LAST IMPACT #%03d · %s > %s\\nPEAK %.3f | RMS %.3f | %.2fs | %s AXIS\\n사진 · 그래프 · CSV · 요약 저장 중...": "OSTATNIE UDERZENIE #%03d · %s > %s\\nPEAK %.3f | RMS %.3f | %.2fs | OŚ %s\\nZapisywanie zdjęcia, wykresu, CSV i podsumowania...",
        "● MONITORING · BACKGROUND READY": "● MONITORING · PRACA W TLE GOTOWA",
        "\\nTelegram : 설정 없음 · Local 저장 완료": "\\nTelegram : brak konfiguracji · zapis lokalny zakończony",
        " 블랙박스 저장 완료": " · zapis blackbox zakończony",
        "PROCESS SHOCK EVENT #": "ZDARZENIE UDERZENIA PROCESU #",
        "Main Direction : ": "Główny kierunek : ",
        "Window : PRE 3 sec + IMPACT CORE + POST 3 sec": "Okno : PRE 3 s + RDZEŃ UDERZENIA + POST 3 s",
        "측정을 종료한 뒤 DATA DOWNLOAD를 실행해주세요.": "Zakończ pomiar przed użyciem POBIERZ DANE.",
        "다운로드할 측정 데이터가 없습니다.": "Brak danych pomiarowych do pobrania.",
        "전체 데이터 ZIP": "Pełny pakiet ZIP",
        "전체 RAW CSV": "Pełny RAW CSV",
        "RUN SUMMARY CSV": "PODSUMOWANIE POMIARU CSV",
        "UNIT SUMMARY CSV": "PODSUMOWANIE MODUŁÓW CSV",
        "IMPACT SUMMARY CSV": "PODSUMOWANIE UDERZEŃ CSV",
        "RAW + 전체 평가 + 사진 + 그래프 + Event CSV": "RAW + pełna ocena + zdjęcia + wykresy + CSV zdarzeń",
        "측정 시작부터 종료까지 모든 X / Y / Z / Total": "Wszystkie X / Y / Z / Total od startu do końca pomiaru",
        "전체 측정시간 / Peak / RMS / 방향 / MCSC": "Cały czas pomiaru / Peak / RMS / kierunek / MCSC",
        "MCSC Unit별 시간 / Avg / Min / Max / RMS / Impact": "Czas modułów MCSC / Avg / Min / Max / RMS / Impact",
        "충격 이벤트별 Peak / RMS / 방향 / 시간": "Peak / RMS / kierunek / czas każdego zdarzenia",
        "충격 당시 사진 + 그래프 + Event CSV + 요약": "Zdjęcie + wykres + CSV + podsumowanie dla uderzenia",
        "저장 위치 : Download / VibrationMonitor": "Lokalizacja : Download / VibrationMonitor",
        "MEASUREMENT DATA DOWNLOAD": "POBIERANIE DANYCH POMIAROWYCH",
        "다운로드 완료\\nDownload/VibrationMonitor/": "Pobieranie zakończone\\nDownload/VibrationMonitor/",
        "다운로드 실패 또는 해당 데이터가 없습니다.": "Pobieranie nieudane lub brak danych.",
        "측정 종료 후 MCSC Timeline Review를 실행해주세요.": "Uruchom przegląd osi MCSC po zakończeniu pomiaru.",
        "측정 후 실제 설비 진행시간에 맞게 Unit 이름/시간을 0.1초 단위로 수정하세요. ": "Po pomiarze popraw nazwy/czasy modułów co 0,1 s zgodnie z rzeczywistym przebiegiem urządzenia. ",
        "적용 시 Production Impact의 Unit 위치와 Unit Summary를 RAW 데이터 기준으로 다시 계산합니다. ": "Po zastosowaniu pozycje modułów i podsumowanie są przeliczane z danych RAW. ",
        "원본 RAW/Event Blackbox는 변경하지 않습니다.": "Oryginalne RAW / Event Blackbox nie są zmieniane.",
        "MCSC TIMELINE REVIEW": "PRZEGLĄD OSI CZASU MCSC",
        "MCSC Timeline 재계산 완료 · 원본 RAW/Blackbox 보존": "Przeliczenie MCSC zakończone · RAW/Blackbox zachowane",
        "AVG=평균 · MIN=최소 · MAX=최대 · RMS=진동수준 · IMP=충격횟수 · SMP=샘플수": "AVG=średnia · MIN=min · MAX=max · RMS=poziom drgań · IMP=uderzenia · SMP=próbki",
        "TOP PRODUCTION IMPACT : 없음": "NAJWIĘKSZE UDERZENIE PRODUKCYJNE : brak",
        "측정시간  %02d:%02d:%02d\\n": "Czas pomiaru  %02d:%02d:%02d\\n",
        "Impact  %d회 · Production %d · Stop/Resume %d\\n": "Impact  %d · Produkcja %d · Stop/Resume %d\\n",
        "최대 Peak  %.3f m/s²\\n": "Maks. Peak  %.3f m/s²\\n",
        "주 충격 방향  %s AXIS\\n": "Główny kierunek uderzenia  OŚ %s\\n",
        "PRODUCTION EVENT PEAK COMPARISON": "PORÓWNANIE PEAK ZDARZEŃ PRODUKCYJNYCH",
        "STOP / RESUME IMPACTS · SEPARATE FROM UNIT RANKING": "UDERZENIA STOP / RESUME · ODDZIELONE OD RANKINGU MODUŁÓW",
        "MCSC UNIT VIBRATION ANALYSIS · AVG / MIN / MAX / RMS": "ANALIZA DRGAŃ MODUŁÓW MCSC · AVG / MIN / MAX / RMS",
        "PRODUCTION UNIT RANKING · MAX / RMS / IMPACT / TIME": "RANKING MODUŁÓW PRODUKCYJNYCH · MAX / RMS / IMPACT / CZAS",
        "MCSC TIMELINE REVIEW / CORRECTION": "PRZEGLĄD / KOREKTA OSI MCSC",
        "↑ ↓  스크롤하여 전체 Unit 비교": "↑ ↓  Przewiń, aby porównać wszystkie moduły",
        "SESSION SUMMARY": "PODSUMOWANIE SESJI",
        "확인": "OK",
        "IMPACT EVENT HISTORY": "HISTORIA ZDARZEŃ UDERZENIOWYCH",
        "저장된 충격 이벤트가 없습니다.": "Brak zapisanych zdarzeń uderzeniowych.",
        "닫기": "Zamknij",
        "IMPACT TREND": "TREND UDERZENIA",
        "IMPACT DETAIL": "SZCZEGÓŁY UDERZENIA",
        "읽기 오류 : ": "Błąd odczytu : ",
        "REMOTE MONITOR": "MONITOR ZDALNY",
        "Remote Monitor 서버를 시작하지 못했습니다.\\n": "Nie udało się uruchomić serwera zdalnego monitoringu.\\n",
        "Wi-Fi/Hotspot 상태를 확인한 뒤 다시 시도해주세요.": "Sprawdź Wi-Fi/Hotspot i spróbuj ponownie.",
        "READ ONLY · 같은 Wi-Fi 또는 Hotspot에서 사용\\n\\n": "PODGLĄD / STEROWANIE · użyj tej samej sieci Wi-Fi lub Hotspot\\n\\n",
        "IP 주소를 찾지 못했습니다.\\n": "Nie znaleziono adresu IP.\\n",
        "두 폰을 같은 Wi-Fi/Hotspot에 연결한 뒤 다시 열어주세요.": "Połącz oba telefony z tą samą siecią Wi-Fi/Hotspot i otwórz ponownie.",
        "다른 폰의 Chrome/Samsung Internet에서 아래 주소를 여세요.\\n\\n": "Na drugim telefonie otwórz poniższy adres w Chrome/Safari.\\n\\n",
        "\\n\\nSTART / PAUSE / RESUME / STOP 원격조작 가능": "\\n\\nDostępne sterowanie zdalne: START / PAUSE / RESUME / STOP",
        "실시간 화면은 보기 전용입니다.": "Ekran czasu rzeczywistego jest tylko do podglądu.",
        "Remote URL 복사 완료": "Adres Remote skopiowany",
        "Remote Monitor 종료": "Monitor zdalny zatrzymany",
    },
    "app/src/main/java/com/example/vibrationmonitor/ProcessShockKeepAliveService.java": {
        "Process Shock Monitoring": "Monitorowanie uderzeń procesu",
        "Keeps continuous equipment impact monitoring active.": "Utrzymuje ciągłe monitorowanie uderzeń urządzenia.",
        "연속 충격 측정이 진행 중입니다.": "Trwa ciągły pomiar uderzeń.",
    },
    "app/src/main/java/com/example/vibrationmonitor/RemoteMonitorServer.java": {
        "<title>Process Shock Remote</title>": "<title>Zdalny monitor uderzeń procesu</title>",
        "PROCESS SHOCK REMOTE": "ZDALNY MONITOR UDERZEŃ",
        "VIEW + CONTROL · Wi-Fi / Hotspot": "PODGLĄD + STEROWANIE · Wi-Fi / Hotspot",
        "CONNECTING...": "ŁĄCZENIE...",
        "Last update : waiting...": "Ostatnia aktualizacja : oczekiwanie...",
        "TOTAL": "CAŁKOWITE",
        "PEAK": "SZCZYT",
        "LIVE VIBRATION": "DRGANIA NA ŻYWO",
        "X / Y / Z / TOTAL · SPEC red line": "X / Y / Z / TOTAL · czerwona linia SPEC",
        "MCSC / IMPACT TIMELINE": "MCSC / OŚ CZASU UDERZEŃ",
        "REMOTE CONTROL": "STEROWANIE ZDALNE",
        "Control PIN required · STOP asks confirmation": "Wymagany PIN sterowania · STOP wymaga potwierdzenia",
        "6-digit Control PIN": "6-cyfrowy PIN sterowania",
        "START MONITORING": "START MONITOROWANIA",
        ">PAUSE<": ">PAUZA<",
        ">RESUME<": ">WZNÓW<",
        "STOP & ANALYZE": "STOP I ANALIZA",
        "LAST IMPACT": "OSTATNIE UDERZENIE",
        "Remote commands are logged on equipment phone.": "Polecenia zdalne są zapisywane w telefonie urządzenia.",
        "Control PIN 6자리를 입력하세요.": "Wprowadź 6-cyfrowy PIN sterowania.",
        "CONTROL CONNECTION ERROR": "BŁĄD POŁĄCZENIA STEROWANIA",
        "STOP & ANALYZE를 원격 실행하시겠습니까?": "Czy zdalnie wykonać STOP I ANALIZĘ?",
        "Last update : ": "Ostatnia aktualizacja : ",
        "s ago": " s temu",
        "● CALIBRATING": "● KALIBRACJA",
        "● LIVE MONITORING": "● MONITOROWANIE NA ŻYWO",
        "● READY / STOPPED": "● GOTOWY / ZATRZYMANY",
        "PROCESS ": "PROCES ",
        "Unit ": "Moduł ",
        "● RECONNECTING...": "● PONOWNE ŁĄCZENIE...",
        "● CONNECTION LOST · RETRYING": "● UTRACONO POŁĄCZENIE · PONAWIANIE",
    },
}

for rel, mapping in files.items():
    path = ROOT / rel
    if not path.exists():
        print("SKIP missing:", rel)
        continue

    text = path.read_text(encoding="utf-8")

    # Longest keys first prevents short replacements from disturbing longer messages.
    for old in sorted(mapping, key=len, reverse=True):
        text = text.replace(old, mapping[old])

    # FINAL_IDENTIFIER_REPAIR_V3
    identifier_repairs = {
        "TYPE_TEXT_FLAG_MULTI_LINIA": "TYPE_TEXT_FLAG_MULTI_LINE",
        "LiniaarLayout": "LinearLayout",
        "setSingleLinia": "setSingleLine",
        "setMinLinias": "setMinLines",
        "drawLinia": "drawLine",
        "readLinia": "readLine",
        "eventLinia": "eventLine",
        "headerLinia": "headerLine",
        "remoteLinia": "remoteLine",
    }
    for bad_name, good_name in identifier_repairs.items():
        text = text.replace(bad_name, good_name)

    path.write_text(text, encoding="utf-8")
    print("PL translated:", rel)
